// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoUploadService_UploadBinary_FullMethodName = "/video_upload.VideoUploadService/UploadBinary"
)

// VideoUploadServiceClient is the client API for VideoUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoUploadServiceClient interface {
	UploadBinary(ctx context.Context, in *VideoData, opts ...grpc.CallOption) (*Response, error)
}

type videoUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoUploadServiceClient(cc grpc.ClientConnInterface) VideoUploadServiceClient {
	return &videoUploadServiceClient{cc}
}

func (c *videoUploadServiceClient) UploadBinary(ctx context.Context, in *VideoData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, VideoUploadService_UploadBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoUploadServiceServer is the server API for VideoUploadService service.
// All implementations must embed UnimplementedVideoUploadServiceServer
// for forward compatibility.
type VideoUploadServiceServer interface {
	UploadBinary(context.Context, *VideoData) (*Response, error)
	mustEmbedUnimplementedVideoUploadServiceServer()
}

// UnimplementedVideoUploadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoUploadServiceServer struct{}

func (UnimplementedVideoUploadServiceServer) UploadBinary(context.Context, *VideoData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBinary not implemented")
}
func (UnimplementedVideoUploadServiceServer) mustEmbedUnimplementedVideoUploadServiceServer() {}
func (UnimplementedVideoUploadServiceServer) testEmbeddedByValue()                            {}

// UnsafeVideoUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoUploadServiceServer will
// result in compilation errors.
type UnsafeVideoUploadServiceServer interface {
	mustEmbedUnimplementedVideoUploadServiceServer()
}

func RegisterVideoUploadServiceServer(s grpc.ServiceRegistrar, srv VideoUploadServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoUploadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoUploadService_ServiceDesc, srv)
}

func _VideoUploadService_UploadBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoUploadServiceServer).UploadBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoUploadService_UploadBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoUploadServiceServer).UploadBinary(ctx, req.(*VideoData))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoUploadService_ServiceDesc is the grpc.ServiceDesc for VideoUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video_upload.VideoUploadService",
	HandlerType: (*VideoUploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBinary",
			Handler:    _VideoUploadService_UploadBinary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
