// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: processing.proto

package processing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoProcessingService_ProcessVideo_FullMethodName = "/video_processing.VideoProcessingService/ProcessVideo"
)

// VideoProcessingServiceClient is the client API for VideoProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoProcessingServiceClient interface {
	ProcessVideo(ctx context.Context, in *VideoData, opts ...grpc.CallOption) (*Response, error)
}

type videoProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoProcessingServiceClient(cc grpc.ClientConnInterface) VideoProcessingServiceClient {
	return &videoProcessingServiceClient{cc}
}

func (c *videoProcessingServiceClient) ProcessVideo(ctx context.Context, in *VideoData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, VideoProcessingService_ProcessVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoProcessingServiceServer is the server API for VideoProcessingService service.
// All implementations must embed UnimplementedVideoProcessingServiceServer
// for forward compatibility.
type VideoProcessingServiceServer interface {
	ProcessVideo(context.Context, *VideoData) (*Response, error)
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

// UnimplementedVideoProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoProcessingServiceServer struct{}

func (UnimplementedVideoProcessingServiceServer) ProcessVideo(context.Context, *VideoData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessVideo not implemented")
}
func (UnimplementedVideoProcessingServiceServer) mustEmbedUnimplementedVideoProcessingServiceServer() {
}
func (UnimplementedVideoProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeVideoProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoProcessingServiceServer will
// result in compilation errors.
type UnsafeVideoProcessingServiceServer interface {
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

func RegisterVideoProcessingServiceServer(s grpc.ServiceRegistrar, srv VideoProcessingServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoProcessingService_ServiceDesc, srv)
}

func _VideoProcessingService_ProcessVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).ProcessVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoProcessingService_ProcessVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).ProcessVideo(ctx, req.(*VideoData))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoProcessingService_ServiceDesc is the grpc.ServiceDesc for VideoProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video_processing.VideoProcessingService",
	HandlerType: (*VideoProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessVideo",
			Handler:    _VideoProcessingService_ProcessVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processing.proto",
}
